const User = [
  {
    _id: '',
    name: '',
    email: '',
    profession: '',
    description: '',
    password: '',
    score: '',
    profilePic: 'https://bootdey.com/img/Content/avatar/avatar7.png',
    otherContactLinks: {
      portfolio: '',
      resume: '',
      linkedin: '',
      github: '',
      discord: '',
    },
    otherPlatformLinks: {
      codeforces: '',
      codechef: '',
      leetcode: '',
      atCoders: '',
    },
    stats: {
      Asked: 30,
      answers: 1,
      groupsJoined: 0,
      freq: 100,
    },
  },
  {
    _id: 'queryhub1',
    name: 'Hello Sharma',
    email: 'darkworld6666@gmail.com',
    profession: 'creator',
    description: 'this is me the creator of this site...',
    password: '123',
    score: 100,
    profilePic: 'https://bootdey.com/img/Content/avatar/avatar7.png',
    otherContactLinks: {
      portfolio: '',
      resume: '',
      linkedin: '',
      github: '',
      discord: '',
    },
    otherPlatformLinks: {
      codeforces: '',
      codechef: '',
      leetcode: '',
      atCoders: '',
    },
    stats: {
      Asked: 30,
      answers: 1,
      groupsJoined: 0,
      freq: 100,
    },
  },
  {
    _id: 'ccqh06',
    name: 'ccqh06 Sharma',
    email: 'darkworld6666@gmail.com',
    profession: 'creator',
    description: 'this is me of this site...',
    password: '123',
    score: 0,
    profilePic: 'https://bootdey.com/img/Content/avatar/avatar7.png',
    otherContactLinks: {
      portfolio: '',
      resume: '',
      linkedin: '',
      github: '',
      discord: '',
    },
    otherPlatformLinks: {
      codeforces: '',
      codechef: '',
      leetcode: '',
      atCoders: '',
    },
    stats: {
      Asked: 30,
      answers: 1,
      groupsJoined: 0,
      freq: 100,
    },
  },
  {
    _id: 'ccqh06',
    name: 'ccqh06 Sharma',
    email: 'darkworld6666@gmail.com',
    profession: 'creator',
    description: 'this is me of this site...',
    password: '123',
    score: 0,
    profilePic: 'https://bootdey.com/img/Content/avatar/avatar7.png',
    otherContactLinks: {
      portfolio: '',
      resume: '',
      linkedin: '',
      github: '',
      discord: '',
    },
    otherPlatformLinks: {
      codeforces: '',
      codechef: '',
      leetcode: '',
      atCoders: '',
    },
    stats: {
      Asked: 30,
      answers: 1,
      groupsJoined: 0,
      freq: 100,
    },
  },
]

export default User
